import type { AgentProfile } from '@/types/agent';

export const agentProfile: AgentProfile = {
  id: 'agent-001',
  slug: 'juan',
  name: 'Juan Dela Cruz',
  referralCode: 'JUAN2025',
  referralLevel: 1,
  tagline: 'Luxury Homestays for Modern Travelers',
  bio: 'With over 5 years of experience in hospitality across the Philippines, I connect travelers with handpicked properties that feel like home. From beachfront villas to city escapes — I make every stay unforgettable.',
  avatarUrl: '/heroimage.png',
  location: 'Davao, Philippines',
  socialLinks: {
    facebook: 'https://facebook.com/juandelacruz',
    messenger: 'https://m.me/juandelacruz',
    whatsapp: 'https://wa.me/639123456789',
  },
  assignedProperties: [
    {
      id: '1',
      title: 'Luxury Beachfront Villa',
      image: '/heroimage.png',
      price: 8500,
      currency: '₱',
      priceUnit: 'night',
      location: 'Boracay, Aklan',
      features: ['Pool', 'Beachfront', 'WiFi', 'Air Conditioning'],
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 1800,
      status: 'Popular Choice',
    },
    {
      id: '2',
      title: 'Modern City Condo',
      image: '/heroimage.png',
      price: 3500,
      currency: '₱',
      priceUnit: 'night',
      location: 'Makati, Metro Manila',
      features: ['Gym Access', 'Pool', 'Parking', 'Security'],
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 650,
      status: 'Available Now',
    },
    {
      id: '3',
      title: 'Cozy Mountain Retreat',
      image: '/heroimage.png',
      price: 4200,
      currency: '₱',
      priceUnit: 'night',
      location: 'Tagaytay, Cavite',
      features: ['Mountain View', 'Garden', 'BBQ Area', 'Pet Friendly'],
      bedrooms: 2,
      bathrooms: 1,
      squareFeet: 1200,
      status: 'Available Now',
    },
    {
      id: '4',
      title: 'Seaside Bungalow',
      image: '/heroimage.png',
      price: 5800,
      currency: '₱',
      priceUnit: 'night',
      location: 'Siargao, Surigao del Norte',
      features: ['Beachfront', 'Surfing', 'WiFi', 'Breakfast'],
      bedrooms: 2,
      bathrooms: 1,
      status: 'Almost Booked',
    },
    {
      id: '5',
      title: 'Heritage House Stay',
      image: '/heroimage.png',
      price: 3200,
      currency: '₱',
      priceUnit: 'night',
      location: 'Vigan, Ilocos Sur',
      features: ['Historic', 'Garden', 'WiFi', 'Kitchen'],
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 1500,
      status: 'New Listing',
    },
    {
      id: '6',
      title: 'Lakeside Cabin',
      image: '/heroimage.png',
      price: 4800,
      currency: '₱',
      priceUnit: 'night',
      location: 'Lake Sebu, South Cotabato',
      features: ['Lake View', 'Kayaking', 'Pet Friendly', 'Fireplace'],
      bedrooms: 2,
      bathrooms: 1,
      squareFeet: 900,
      status: 'Available Now',
    },
  ],
};
